### ISSUE TITLE
Bot does not inform about disabled DM

### ISSUE THREAD

**Issue by Meerkat25** [Heptagram-Bot/Heptagram#215] opened 2021-07-07 20:31 UTC
When running the `help` command, the bot tries to send a private message, but when the user has this option blocked, the bot informs about the error without giving a reason.

![IMG_20210707_223413.jpg](https://user-images.githubusercontent.com/87095484/124825088-79a4ab00-df73-11eb-991c-e8a307f302e1.jpg)

**Comment by j-dogcoder** [comment] 2021-07-07 20:57
Duplicate of #216

**Closed** 2021-07-07 20:59 UTC
Labels: duplicate, 🚩 Closed 🚩
